### PR TITLE
chatbot

### PR DESCRIPTION
**Pull request by lunek1**
## Netlify link
https://taupe-duckanoo-54326b.netlify.app/

## Collaborators
Solo

### CODE REVIEW

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Cornelia, good job with your chatbot! 🤖 The idea is really cute and your code looks well structured ⭐ 
However, I see that the user is not prompted to enter the name, that was required. Most importantly in every chatbot there is some kind of delay in between answer and question. Right now the `setTimeout() `is not applied correctly to the bot answer, take a look at the original code we provided again and if you need help don't hesitate to reach out on StackOverflow. Thank you 👍

**Comment by NellaMori** [comment]
Hey Cornelia, please link a working link for your deployed :)

**Comment by lunek1** [comment]
Hi! Is it working now? It's working for me. 🌻

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by HIPPIEKICK** [comment]
I get Site Not Found on this one: https://65d211ffb996fd5de583099b--eloquent-syrniki-cf72c0.netlify.app/

**Comment by lunek1** [comment]
Hi!
This is the link I updated on my readme on github:
https://incandescent-medovik-162441.netlify.app/

Sent with [Proton Mail](https://proton.me/) secure email.

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Cornelia, great you fixed the name input! Now only the delayed needs to be fixed and you're good to go ⭐

**Comment by lunek1** [comment]
> Hi Cornelia, great you fixed the name input! Now only the delayed needs to be fixed and you're good to go ⭐

How do I do the delay? Cause I thought I had a delay on the first greet message from the bot. I'm a bit clueless atm.

**Comment by NellaMori** [comment]
you had it in the code example, looks like this:

`setTimeout(greetUser, 1000)`

so you need to wrap your function that you want to delay in a `setTimeout` method and specify the delay in milliseconds. Hope this helps ⭐

**Comment by lunek1** [comment]
> you had it in the code example, looks like this:
> 
> `setTimeout(greetUser, 1000)`
> 
> so you need to wrap your function that you want to delay in a `setTimeout` method and specify the delay in milliseconds. Hope this helps ⭐

I've changed setTimout to 500 on the greeting function instead of 1000. Was that what you needed me to change? 😊

**Comment by NellaMori** [comment]
Hi Cornelia, this was [our example](https://technigo-chatbot.netlify.app/) - you see how every response is delayed. Now, you need to identify in your code which are the functions responsible for giving a bot response, and wrap those functions into a `setTimeout(yourFunction, 1000)` method, for example in your code you have ` askPreference()`, `askSetting() `etc. If you need more info, check your classmates [previous pull requests](https://github.com/Technigo/project-chatbot/pulls?q=is%3Aopen+is%3Apr+review%3Aapproved) to see how they implemented it :)

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
See the convo thread :)

**Comment by lunek1** [comment]
> Hi Cornelia, this was [our example](https://technigo-chatbot.netlify.app/) - you see how every response is delayed. Now, you need to identify in your code which are the functions responsible for giving a bot response, and wrap those functions into a `setTimeout(yourFunction, 1000)` method, for example in your code you have ` askPreference()`, `askSetting() `etc. If you need more info, check your classmates [previous pull requests](https://github.com/Technigo/project-chatbot/pulls?q=is%3Aopen+is%3Apr+review%3Aapproved) to see how they implemented it :)

Okey all responses is delayed now.

**Review by AntonellaMorittu — APPROVED** [review]

**Pull request closed without merging**
